# Generated by Django 6.0.3 on 2026-03-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hw_project", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="task",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="subtask",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterModelTable(
            name="category",
            table="task_manager_category",
        ),
        migrations.AlterModelTable(
            name="subtask",
            table="task_manager_subtask",
        ),
        migrations.AlterModelTable(
            name="task",
            table="task_manager_task",
        ),
    ]
