# Generated by Django 6.0.3 on 2026-03-08 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hw_project", "0002_alter_task_unique_together_alter_subtask_title_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subtask",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "SubTask",
                "verbose_name_plural": "SubTasks",
            },
        ),
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
            },
        ),
    ]
