# Generated by Django 6.0.3 on 2026-05-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hw_project", "0003_alter_subtask_options_alter_task_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="deleted_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
