# Generated by Django 6.0.3 on 2026-05-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hw_project", "0005_alter_category_options_subtask_author_task_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="last_notified_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
